Repository callback-demons/callback-news, pull requests merged in 2020-05, with the labels that each got.

#36 Mobile menu hamburger button
  .gitignore
  components/Footer.js
  components/Hamburger.js
  components/Header.js
  components/Hero.js
  components/Layout.js
  components/MobileMenu.js
  components/PostItem.js
  components/PostItemList.js
  pages/full.js
  pages/index.js
  styled/themes/light.js
  utils/mocks/rss.json
Labels: feature

#45 Merge CategoryItem and test in home
  components/CategoryItem.js
  components/Header.js
  pages/index.js
  styled/mixins/index.js
  styled/themes/light.js
Labels: bug

#44 Category item
  components/CategoryItem.js
  styled/mixins/index.js
  styled/themes/light.js
Labels: feature

#50 CategoryItemList Component
  components/CategoryItem.js
  components/CategoryItemList.js
  components/Header.js
  pages/index.js
  styled/themes/light.js
  utils/mocks/categories.json
Labels: feature

#61 Post content
  components/Header.js
  components/Heart.js
  components/InfoPost.js
  components/Markdown.js
  components/PostCard.js
  components/PostContent.js
  components/PostItem.js
  package-lock.json
  package.json
  pages/post.js
  styled/globalStyles.js
  utils/mocks/post.json
  utils/mocks/rss.json
Labels: feature

#71 :lipstick: (PostItem): Fix layout based on design
  components/Avatar.js
  components/InfoPost.js
  components/PostItem.js
  components/PostItemList.js
  utils/mocks/rss.json
Labels: feature

#72 CommentInput Component
  components/CommentInput.js
  styled/mixins/index.js
  styled/themes/light.js
Labels: feature

#70 Comment Component
  components/Comment.js
  package-lock.json
  package.json
  styled/globalStyles.js
  styled/mixins/index.js
Labels: feature

#77 Creating UserMenu Component
  components/Header.js
  components/MobileMenu.js
  components/UserMenu.js
  styled/globalStyles.js
Labels: feature

#78 (InfoPost): Fix InfoPost component to be responsive
  components/InfoPost.js
  components/PostContent.js
  pages/index.js
Labels: bug

#79 (PostItem): Fixing old styles
  components/PostItem.js
Labels: design

#80 (Post): Fetch post data from fake Api
  components/InfoPost.js
  components/PostContent.js
  components/PostItem.js
  pages/post.js
Labels: feature

#88 Creating Modal Component
  components/ClientPortal.js
  components/Header.js
  components/Modal.js
  components/UserMenu.js
  hooks/useModal.js
  pages/_document.js
Labels: feature

#86 Comments section on Post Page
  components/CommentInput.js
  components/CommentsSection.js
  package-lock.json
  package.json
  pages/post.js
Labels: feature

#93 Creating SkeletonText and SkeletonParagraph Components
  components/SkeletonParagraph.js
  components/SkeletonText.js
Labels: feature

#98 Babel configuration error
  pages/full.js
Labels: bug

#94 (PostItemSkeleton): Add text mock to PostItemSkeleton
  components/AsyncImage.js
  components/CategoryItem.js
  components/CategoryItemSkeleton.js
  components/CircleSkeleton.js
  components/HeartSkeleton.js
  components/InfoPostSkeleton.js
  components/PostItem.js
  components/PostItemList.js
  components/PostItemSkeleton.js
  components/SkeletonParagraph.js
  components/SkeletonText.js
  hooks/useLoading.js
Labels: design

#101 Implementing Login Form on the Modal
  components/Button.js
  components/CommentInput.js
  components/Header.js
  components/LabelInput.js
  components/LoginForm.js
  components/Modal.js
  components/UserMenu.js
  hooks/useModal.js
Labels: feature

#105 Creating Profile Page
  components/LabelInput.js
  components/Modal.js
  components/UserData.js
  pages/profile.js
Labels: feature

#106 Develop
  PULL_REQUEST_TEMPLATE.md
  README.md
  __test__/global.test.js
  components/AsyncImage.js
  components/Avatar.js
  components/Avatar.test.js
  components/Button.js
  components/CategoryItem.js
  components/CategoryItemSkeleton.js
  components/CircleSkeleton.js
  components/ClientPortal.js
  components/Comment.js
  components/CommentInput.js
  components/CommentsSection.js
  components/Header.js
  components/HeartSkeleton.js
  components/InfoPost.js
  components/InfoPostSkeleton.js
  components/LabelInput.js
  components/LoginForm.js
  components/MobileMenu.js
  components/Modal.js
  components/PostContent.js
  components/PostItem.js
  components/PostItemList.js
  components/PostItemSkeleton.js
  components/RegisterForm.js
  components/SkeletonParagraph.js
  components/SkeletonText.js
  components/UserData.js
  components/UserMenu.js
  hooks/useLoading.js
  hooks/useModal.js
  package-lock.json
  package.json
  pages/_document.js
  pages/full.js
  pages/index.js
  pages/post.js
  pages/profile.js
  routes.js
  server.js
  setupTest.js
  styled/globalStyles.js
  styled/mixins/index.js
  styled/themes/light.js
  utils/mocks/rss.json
Labels: feature

#107 (MultipleBugs): Fixing bugs
  components/Hamburger.js
  components/Header.js
  components/MobileMenu.js
  components/UserData.js
  components/UserMenu.js
  hooks/useToggle.js
Labels: bug

#108 configuration jenkins file
  Jenkinsfile
Labels: infrastructure

#109 Hero
  components/AsyncImage.js
  components/Button.js
  components/Hero.js
  components/HeroElement.js
  components/HeroElementSkeleton.js
  components/carousel/CarouselButtons.js
  components/carousel/IndicatorDots.js
  package-lock.json
  package.json
  pages/index.js
Labels: feature

#110 <Footer /> component
  components/Footer.js
  components/Layout.js
Labels: feature

#113 :bug: (PostItem): Fix post items styles
  components/InfoPost.js
  components/PostItem.js
  components/PostItemSkeleton.js
Labels: bug

#117 Handling Profile Page Data
  components/Button.js
  components/EyeIcon.js
  components/LabelInput.js
  components/UserData.js
  pages/profile.js
Labels: feature

#120 (Error): Handle server errors in ErrorPage
  components/PostItem.js
  components/PostItemList.js
  components/SearchBar.js
  pages/_error.js
  styled/themes/light.js
Labels: feature

#122 Small visual bugs part 1
  components/Button.js
  components/CategoryItem.js
  components/CategoryItemList.js
  components/CommentInput.js
  components/Footer.js
  components/Header.js
  components/Heart.js
  components/Hero.js
  components/HeroElement.js
  components/Layout.js
  components/LoginForm.js
  components/MobileMenu.js
  components/Modal.js
  components/PasswordRecovery.js
  components/PostItemList.js
  components/RegisterForm.js
  components/UserData.js
  components/carousel/CarouselButtons.js
  components/carousel/IndicatorDots.js
  package.json
  pages/_error.js
  pages/index.js
  styled/mixins/index.js
Labels: bug

#123 Creating Basic Category Page
  components/CategoryItemList.js
  components/DottedLine.js
  components/UserMenu.js
  pages/category.js
  routes.js
Labels: feature

#126 Improving Search Bar
  components/EyeIcon.js
  components/MobileMenu.js
  components/SearchBar.js
  components/SearchIcon.js
Labels: feature

#127 Develop
  Jenkinsfile
  components/AsyncImage.js
  components/Button.js
  components/CategoryItem.js
  components/CategoryItemList.js
  components/CommentInput.js
  components/DottedLine.js
  components/EyeIcon.js
  components/Footer.js
  components/Hamburger.js
  components/Header.js
  components/Heart.js
  components/Hero.js
  components/HeroElement.js
  components/HeroElementSkeleton.js
  components/InfoPost.js
  components/LabelInput.js
  components/Layout.js
  components/LoginForm.js
  components/MobileMenu.js
  components/Modal.js
  components/PasswordRecovery.js
  components/PostItem.js
  components/PostItemList.js
  components/PostItemSkeleton.js
  components/RegisterForm.js
  components/SearchBar.js
  components/SearchIcon.js
  components/UserData.js
  components/UserMenu.js
  components/carousel/CarouselButtons.js
  components/carousel/IndicatorDots.js
  hooks/useToggle.js
  package-lock.json
  package.json
  pages/_error.js
  pages/category.js
  pages/index.js
  pages/profile.js
  pages/recover.js
  routes.js
  styled/mixins/index.js
  styled/themes/light.js
Labels: feature

#129 Handling Forms data
  components/LoginForm.js
  components/PasswordRecovery.js
  components/RegisterForm.js
  components/UserData.js
  components/UserMenu.js
  hooks/useForm.js
Labels: feature

#132 Develop to Master for Testing Jenkins
  components/LoginForm.js
  components/PasswordRecovery.js
  components/PostContent.js
  components/RegisterForm.js
  components/SkeletonParagraph.js
  components/UserData.js
  components/UserMenu.js
  hooks/useForm.js
  pages/post.js
Labels: feature

#135 Integration Backend with Frontend News and Categories
  components/Avatar.js
  components/HeroElement.js
  components/LoginForm.js
  components/PostItem.js
  components/UserData.js
  components/UserMenu.js
  pages/category.js
  pages/index.js
Labels: feature

#136 Small bugs part 3
  components/Footer.js
  components/InfoPost.js
  components/PostCard.js
  components/PostItemList.js
  pages/index.js
  styled/globalStyles.js
Labels: bug

#137 :bug: Minor fixes
  components/AsyncImage.js
  components/Header.js
  components/Hero.js
  components/HeroElement.js
  components/Layout.js
  components/PostContent.js
  components/PostItem.js
  pages/_error.js
Labels: bug

#139 Updating Category Page Title and Profile Page Navigation
  components/CategoryItem.js
  components/Header.js
  components/UserMenu.js
  pages/category.js
  pages/profile.js
Labels: feature

#142 Creating and Handling Notifications
  components/Button.js
  components/ClientPortal.js
  components/MobileMenu.js
  components/Modal.js
  components/Notification.js
  components/PasswordRecovery.js
  components/RegisterForm.js
  components/UserData.js
  components/UserMenu.js
  pages/_document.js
Labels: feature

#143 Manage local storage to save user session
  components/Hamburger.js
  components/Header.js
  components/LoginForm.js
  components/UserMenu.js
Labels: feature

#144 Testing start
  components/AsyncImage.test.js
  components/Button.test.js
  components/CategoryItem.test.js
  components/CategoryItemList.test.js
  components/CategoryItemSkeleton.test.js
  components/CircleSkeleton.test.js
  components/ClientPortal.test.js
  components/Comment.test.js
  components/CommentInput.test.js
  components/CommentsSection.test.js
  mocks/categories.json
  mocks/news.json
  package-lock.json
  package.json
Labels: testing

#146 Register Form Integration with the API
  components/LoginForm.js
  components/Notification.js
  components/PostItemList.js
  components/RegisterForm.js
  hooks/useForm.js
  pages/category.js
  pages/index.js
  styled/globalStyles.js
  utils/validations.js
Labels: feature

#147 Integration Development to Production
  components/AsyncImage.js
  components/AsyncImage.test.js
  components/Avatar.js
  components/Button.js
  components/Button.test.js
  components/CategoryItem.js
  components/CategoryItem.test.js
  components/CategoryItemList.test.js
  components/CategoryItemSkeleton.test.js
  components/CircleSkeleton.test.js
  components/ClientPortal.js
  components/ClientPortal.test.js
  components/Comment.test.js
  components/CommentInput.test.js
  components/CommentsSection.test.js
  components/Footer.js
  components/Hamburger.js
  components/Header.js
  components/Hero.js
  components/HeroElement.js
  components/InfoPost.js
  components/Layout.js
  components/LoginForm.js
  components/MobileMenu.js
  components/Modal.js
  components/Notification.js
  components/PasswordRecovery.js
  components/PostCard.js
  components/PostContent.js
  components/PostItem.js
  components/PostItemList.js
  components/RegisterForm.js
  components/UserData.js
  components/UserMenu.js
  components/carousel/CarouselButtons.js
  hooks/useForm.js
  mocks/categories.json
  mocks/news.json
  package-lock.json
  package.json
  pages/_document.js
  pages/_error.js
  pages/category.js
  pages/index.js
  pages/post.js
  pages/profile.js
  styled/globalStyles.js
  utils/validations.js
Labels: feature

#150 (Develop): Stop tracking lock files
  .gitignore
  package-lock.json
Labels: bug

#152 Updating Styles and some Visual Updates
  components/CategoryItem.js
  components/CategoryItemList.js
  components/CategoryItemSkeleton.js
  components/InfoPost.js
  components/Layout.js
  components/PostCard.js
  components/PostContent.js
  components/PostItem.js
  components/PostItemList.js
  components/RegisterForm.js
  components/SearchBar.js
  components/UnderlinedContent.js
  components/UserData.js
  components/UserMenu.js
  components/carousel/CarouselButtons.js
  components/carousel/Hero.js
  components/carousel/HeroElement.js
  components/carousel/HeroElementSkeleton.js
  pages/category.js
  pages/index.js
  styled/globalStyles.js
Labels: bug, feature, maintenance

#153 Integration Develop to Production
  components/CategoryItem.js
  components/CategoryItemList.js
  components/CategoryItemSkeleton.js
  components/Header.js
  components/InfoPost.js
  components/Layout.js
  components/LoginForm.js
  components/PostCard.js
  components/PostContent.js
  components/PostItem.js
  components/PostItemList.js
  components/RegisterForm.js
  components/SearchBar.js
  components/UnderlinedContent.js
  components/UserData.js
  components/UserMenu.js
  components/carousel/CarouselButtons.js
  components/carousel/Hero.js
  components/carousel/HeroElement.js
  components/carousel/HeroElementSkeleton.js
  hooks/useUserContext.js
  pages/category.js
  pages/index.js
  styled/globalStyles.js
  utils/UserContext.js
Labels: bug, feature
