Repository callback-demons/callback-news, pull requests merged in 2020-06, with the labels that each got.

#155 Update Like Functionality
  components/InfoPost.js
  components/PostContent.js
  components/PostItem.js
Labels: feature

#157 Comments Flow
  components/Comment.js
  components/CommentsSection.js
  components/Layout.js
  components/LoginForm.js
  components/RegisterForm.js
  hooks/useForm.js
  pages/post.js
  utils/validations.js
Labels: feature

#158 Save token in session
  components/InfoPost.js
  package.json
  pages/post.js
Labels: bug

#160 Search page
  pages/search.js
Labels: feature

#159 Integration Development to master
  __test__/components/AsyncImage.test.js
  __test__/components/Avatar.test.js
  __test__/components/Button.test.js
  __test__/components/CategoryItem.test.js
  __test__/components/CategoryItemList.test.js
  __test__/components/CategoryItemSkeleton.test.js
  __test__/components/CircleSkeleton.test.js
  __test__/components/ClientPortal.test.js
  __test__/components/Comment.test.js
  __test__/components/CommentInput.test.js
  __test__/components/CommentsSection.test.js
  __test__/components/Layout.test.js
  components/Comment.js
  components/CommentsSection.js
  components/Header.js
  components/InfoPost.js
  components/Layout.js
  components/LoginForm.js
  components/PostContent.js
  components/PostItem.js
  components/RegisterForm.js
  hooks/useForm.js
  package.json
  pages/post.js
  pages/search.js
  utils/validations.js
Labels: bug, feature

#164 Fixing data flow
  components/InfoPost.js
  components/LoginForm.js
  components/RegisterForm.js
  components/SearchBar.js
  hooks/useForm.js
  pages/post.js
  utils/validations.js
Labels: bug, feature

#165 Fik Likes in Home
  pages/index.js
Labels: feature

#167 Linking tags and Fetching Popular News
  components/MobileMenu.js
  components/PostItem.js
  pages/index.js
Labels: feature

#169 Integration Development to Master
  components/CategoryItem.js
  components/InfoPost.js
  components/LoginForm.js
  components/MobileMenu.js
  components/PostItem.js
  components/RegisterForm.js
  components/SearchBar.js
  components/UserData.js
  hooks/useForm.js
  pages/index.js
  pages/post.js
  pages/profile.js
  pages/search.js
  utils/validations.js
Labels: bug, feature

#171 Linking search page
  components/SearchBar.js
  pages/index.js
  pages/search.js
Labels: bug

#172 Integration Development to Production
  __test__/components/CategoryItem.test.js
  __test__/components/CategoryItemList.test.js
  __test__/components/CategoryItemSkeleton.test.js
  __test__/components/CircleSkeleton.test.js
  __test__/components/ClientPortal.test.js
  __test__/components/Comment.test.js
  __test__/components/CommentInput.test.js
  __test__/components/CommentsSection.test.js
  __test__/components/Layout.test.js
  components/CategoryItem.js
  components/Layout.js
  components/PostItem.js
  components/SearchBar.js
  components/carousel/HeroElement.js
  pages/index.js
  pages/search.js
Labels: bug
